export const enviroment = {
  port: 4269,
  messageIdentifier: "chat message",
  destroySessionDelay: 300000,
  maxPictures: 20,
  maxDocuments: 10,
  basePath: "/deviceconnect",
  ssl: true,
  animalNames: [
    "Ant",
    "Caterpillar",
    "Fly",
    "Lion",
    "Snail",
    "Aquarium",
    "Chicken",
    "Frog",
    "Mite",
    "Spider",
    "Badger",
    "Corgi",
    "Giraffe",
    "Mosquito",
    "Starfish",
    "Bat",
    "Cow",
    "Gorilla",
    "Nemo",
    "Stork",
    "Bear",
    "Crab",
    "Grasshopper",
    "Octopus",
    "Tentacles",
    "Beaver",
    "Deer",
    "Hornet",
    "Panda",
    "Turtle",
    "Bee",
    "Dinosaur",
    "Horse",
    "Pig",
    "Unicorn",
    "Bird",
    "Dog",
    "Hummingbird",
    "Prawn",
    "Wasp",
    "BlueFish",
    "Dolphin",
    "Insect",
    "Puffin",
    "Whale",
    "Bug",
    "Dragonfly",
    "Kangaroo",
    "Rabbit",
    "Wolf",
    "Bull",
    "Duck",
    "Kiwi",
    "Rhinoceros",
    "Bumblebee",
    "Elephant",
    "Ladybird",
    "Seahorse",
    "Butterfly",
    "Falcon",
    "Lama",
    "Shark",
    "Cat",
    "Fish",
    "Leopard",
    "Sheep",
  ],
};
